### ISSUE TITLE
Need to add a space between the value and cm/kg

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#10]
**Reported on:** https://12weekstosleek.feedmybeta.com/my-plan/

Need to add a space between the value to make it neater and also change the Kg's to kg

![Screenshot 2019-09-13 at 13 49 11](https://user-images.githubusercontent.com/35291167/64860449-78332180-d62d-11e9-993a-a3f442961abc.png)

**Comment by viscosho** [comment]
@jacquesvdhorst please test, this was fixed here: https://github.com/lightspeeddevelopment/lsx-health-plan/commit/f19efc0d47f5c398f22798ba107f0ef33e4e0220
