### ISSUE TITLE
Video modal won’t close on mobile device

### ISSUE THREAD

**Issue by garthglaum** [lightspeeddevelopment/lsx-health-plan#13]
The exercise video modal will not close on mobile devices.  There is no close button and tapping outside of the modal won't close it either.

![IMG_1112](https://user-images.githubusercontent.com/31071701/66494541-1c3aac00-eab8-11e9-8e3c-0f3339467f34.PNG)

**Comment by jacquesvdhorst** [comment]
I've fixed this issue with https://github.com/lightspeeddevelopment/lsx-health-plan/commit/69b7f1e30b2079aa1a5a62350c9aeebd34fc100b
