### ISSUE TITLE
Add options to show full content, excerpt or no content for exercise modals

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-health-plan#130]
### Is your enhancement related to a problem? Please describe.
Some sites don't need to link exercises to a single exercise page, so they just show the exercise info on a modal on the workouts tab, so there should be an option to show full content, excerpt or no content for modals

### Additional context
Add the new option here: 
<img width="741" alt="Screen Shot 2020-06-17 at 4 28 06 PM" src="https://user-images.githubusercontent.com/3129483/84947046-94318b00-b0b7-11ea-98a0-eba0d8b76c4c.png">

**Comment by krugazul** [comment]
@viscosho 

- [x] Here is where the setting will be registered - [https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/post-types/class-workout.php#L332](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/post-types/class-workout.php#L332)
- [x] This is the workout grid template,  this is where you will call the setting - [https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/partials/workout-grid.php#L16](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/partials/workout-grid.php#L16)
- [x] Then you pass that setting in an `$args = array()` to the button function,  replacing the `false` at the end. - [https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/partials/workout-grid.php#L58](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/partials/workout-grid.php#L58)
- [x] You will need to make sure there is a default parameter set here, maybe called `modal_content` - [https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/includes/template-tags/exercise.php#L63](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/includes/template-tags/exercise.php#L63)
- [ ] The content / excerpt is added to the modal here - [https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/includes/template-tags/exercise.php#L102](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/includes/template-tags/exercise.php#L102)
