### ISSUE TITLE
Add a setting to make downloads global vs allocated individually to posts

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-health-plan#14]
Add a setting to make downloads global vs allocated individually to posts
There should be both options:
- [x] A user should be able to configure downloads on a per post basis
- [x] A user should be able to assign global download files 

NB: All download files must be secure no matter what method is used.

**Comment by krugazul** [comment]
I have added in fields to the [settings](https://lsx-health-plan.lsdev.biz/wp-admin/options-general.php?page=lsx_health_plan_options) page which lets you set a default warm up, workout, meal plan and recipe download.
![global-downloads](https://user-images.githubusercontent.com/1805603/67771785-9e881180-fa61-11e9-8019-00f0cd6fae05.png)

Once that has been set, it will pull through to all of the [day](https://lsx-health-plan.lsdev.biz/plan/day-56/) plan boxes. See the example below, a global meal plan set for all plans.
![default-meal-plan](https://user-images.githubusercontent.com/1805603/67772025-09d1e380-fa62-11e9-85ea-bcc763d29ff1.png)

**Comment by krugazul** [comment]
@viscosho, I am closing this issue,  @ignusvermaak has tested it.
