### ISSUE TITLE
Multiplan templates - Plans Landing page - logged in

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-health-plan#140]
### Description
There is a new design for site with multiple plans.

### To do
- [x] Update the Plans Landing page template to reflect these designs.
- [x] The new design should only display if there are multiple plans.

### Designs
Desktop: https://projects.invisionapp.com/d/#/console/17434990/425079303/preview

### Additional context
![Health Plans - landing page - Logged in](https://user-images.githubusercontent.com/31090573/88260395-942f3700-ccc4-11ea-9837-2f1d67f4013e.jpg)

**Comment by ashleyshaw** [comment]
@viscosho can we close this issue? I think that the plans archive works fine.

**Comment by viscosho** [comment]
Added on this merge https://github.com/lightspeeddevelopment/lsx-health-plan/commit/62b89f5182c87f09c5307bf63c2839b0580a8dc4
