### ISSUE TITLE
When no tips are present on the Meal Plan the box should not appear

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#15]
Currently when no Tips are associated with a Meal Plan then the Tips box still shows. This needs to be hidden if no content is inside it.

![image](https://user-images.githubusercontent.com/35291167/66927530-3e8c7680-f030-11e9-9d0f-310ded99dc44.png)

**Comment by krugazul** [comment]
**Description of the Change**
A function has been added to check to see if tips are attached to a specified plan. This returns a boolean variable.

**Benefits**
 - Slightly better performance, as there is less HTML outputting on the page.  As well as there is no empty grey block

![Screenshot 2020-01-20 at 15 51 22](https://user-images.githubusercontent.com/1805603/72732480-78749800-3b9e-11ea-980b-2ae6e594bb6f.png)
