### ISSUE TITLE
Paid Health Plans for WooCommerce

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#154]
### Add WooCommerce Integration Support

- [x] Site owners need to be able to sell any individual plans and restrict plan content is only be accessible to paying members.

### Describe the solution you'd like

**Plan Types** 

- [x] Full health plan that includes both workouts with exercises & meals with recipes.
- [x] Meal plan only.
- [x] Workout plan only.

**Single Plan Frontend Template**

- [x] On the Single Plan template display an "add to cart" or "sign up now" button on the plan allowing the user to buy the individual plan.

**Content restrictions**

- [x] _**Scenario 1:**_ Only logged in users who have paid for the full plan can view meal, recipe, workout & exercise content. 
- [x] Example: User buys plan 1, but not plan 2, they will be able to access all of the content in plan 1, but none of the content in plan 2.
- [x] _**Scenario 2:**_ Restrict access to any plans that have not purchased and display a text message saying "signup to access plan", the message needs to link the single plan page, which will allow the user to 

### Designs

![Single Plan Page - Logged out](https://user-images.githubusercontent.com/1805352/89463254-f54c1580-d76e-11ea-9e8c-082640e78e12.png)

### Nice to have functionality

- [x]  NB:  These tasks.

**Plan Previews:**

- [x] "Free Preview" option to allow users to take a peek at a limited number of plan pages content.

**WooCommerce Memberships Extension Integration:**

- [x] Research more about how to implement a Memberships integration.
- [x] Sell Health Plan access using the and a membership plan product. 

**WooCommerce Subscriptions Extension Integration:**

- [x] Research whether any special Subscriptions support needs to be added for the Plans Product to work 100% with a Subscription Product.

**Comment by krugazul** [comment]
## Content Restriction Guide  (comment is still being updated)
### [Membership Messages (WooCommerce Settings)](https://lsx-health-plan.lsdev.biz/wp-admin/admin.php?page=wc-settings&tab=memberships&section=messages)
- Change the restriction messages to be more generic

### [Plans Archive Frontend](https://lsx-health-plan.lsdev.biz/plans/)
1: You will see all plans available
2: The button goes through 3 states.
  - If you are logged out or do not have access to the plan, the button will be an "Add to Cart" button.
  - If you have purchased access then it will be disabled, but still linked to the single plan with the text "Already signed up"
  - If the plan is "free", meaning no products or membership is assigned, then it will be a standard "View" button, linking through to the single plan.

### [Single Plans (edit screen)](https://lsx-health-plan.lsdev.biz/wp-admin/post.php?post=5594&action=edit&classic-editor&classic-editor__forget)
1: You will need to connect your plan to a product via the "Products" meta box that appears in the sidebar of the screen.
2: You will need to assign the membership plan to the page via the "Memberships" metabox.

**Comment by viscosho** [comment]
Added on this merge https://github.com/lightspeeddevelopment/lsx-health-plan/commit/62b89f5182c87f09c5307bf63c2839b0580a8dc4
