### ISSUE TITLE
Add an custom field for "Exercise Title" to the exercise custom field groups on Single Workouts

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#166]
### Challenge. 

- Currently, there is a lack of flexibility when connecting exercises to a workout exercise group.
- If an exercise has a slight variation on a single workout, is necessary to create a new exercise with this variation. This ends up being a problem because there are so many exercises with the same image and description but with a small variation being created.

### Solution: 
Add an additional custom field for setting a custom exercise title, description and image.
1 field for title, 1 field for image and 1 multiline text field for description.

Three scenarios when adding an exercise to a set:

### Scenario 1:

- Add exercise with only the "title" & "reps/dist/time" text fields filled in.
  - _**Display:**_ Exercise title will display whatever the title text field contains and will not be links.

### Scenario 2:

- Add exercise with an exercise post connected AND the "title" & "reps/dist/time" text fields filled in.
  - _**Display:**_ Exercise title will display whatever the title of the linked exercise post AND that title will be linked to a modal or single exercise depending on config. 

### Scenario 3:

- Add exercise with an exercise post connected AND only the "reps/dist/time" text fields filled. The result is now we can edit the exercise link text using the new custom text field.
  - _**Display:**_ Exercise title will display whatever the title text field contains and it will be linked to a modal or single exercise depending on config.  

### Screenshots

<img width="938" alt="Screen Shot 2020-08-13 at 8 20 23 AM" src="https://user-images.githubusercontent.com/1805352/90139866-3482f380-dd79-11ea-8430-18163e78b9be.png">

<img width="1163" alt="Screen Shot 2020-08-13 at 8 33 32 AM" src="https://user-images.githubusercontent.com/1805352/90139881-38af1100-dd79-11ea-8489-2620eb202cac.png">

**Comment by viscosho** [comment]
Added on this merge https://github.com/lightspeeddevelopment/lsx-health-plan/commit/62b89f5182c87f09c5307bf63c2839b0580a8dc4
