### ISSUE TITLE
Connected Post Types are duplicating when saving 

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#17]
When you edit a `Meal Plan` for example, and add in a new `Download` or `Day Plan`, and click save,  the connected item will be duplicated.   See example below.

1:)  Edit [meal plan 3](https://lsx-health-plan.lsdev.biz/wp-admin/post.php?post=2598&action=edit&classic-editor) and connect it to Day 4.
![meal-plan-edit](https://user-images.githubusercontent.com/1805603/67745648-74b4f780-fa2d-11e9-9df0-cf97f2d54f85.png)

2:)  View the connected "[Day](https://lsx-health-plan.lsdev.biz/wp-admin/post.php?post=3001&action=edit&classic-editor)" attached. You will see the connected "items" duplicate the attached meal plan
![day-plan-edit](https://user-images.githubusercontent.com/1805603/67745789-c8274580-fa2d-11e9-9ddb-ad4226f9601e.png)

**Comment by viscosho** [comment]
@krugazul  I have tested the branch containing this fix on my local, I have tested several meal plans and other post types, adding and deleting content, nothing is duplicated.
