### ISSUE TITLE
Meal Plan does not interpret HTML

### ISSUE THREAD

**Issue by ignusvermaak** [lightspeeddevelopment/lsx-health-plan#18]
- See https://verloorjouboep.feedmybeta.com/plan/maandag/meal/ and the attached screenshot
- Link to edit screen https://verloorjouboep.feedmybeta.com/wp-admin/post.php?post=4935&action=edit&classic-editor
- The text inside the dinner field contains 2 paragraphs separated by a non-breaking space, that should appear separated on the frontend.
- It should be possible to add multiple paragraphs to a mealtime entry if it is required.

**Related Links**
- BugHerd: https://www.bugherd.com/projects/180675/tasks/1

![Backend- Meal Plan does not interpret HTML properly](https://user-images.githubusercontent.com/3509933/67773784-ef4d3980-fa64-11e9-963e-3cc0cf5e5ac5.png)
![Meal Plan does not interpret HTML properly](https://user-images.githubusercontent.com/3509933/67773785-ef4d3980-fa64-11e9-8283-65d327c1f8fb.png)

**Comment by krugazul** [comment]
@ignusvermaak I have applied `the_content` filter to the meal plan outputs,  this adds in the `<p>` tags, it should also be able to run shortcodes now.  NB I removed the `&nbsp;` from the text.
![fixed-formatting](https://user-images.githubusercontent.com/1805603/67777891-1575d800-fa6b-11e9-9967-5bc41553c1e7.png)

**Comment by ignusvermaak** [comment]
Tested and the issue is fixed.
