### ISSUE TITLE
Workout connect video field only works after save

### ISSUE THREAD

**Issue by ignusvermaak** [lightspeeddevelopment/lsx-health-plan#19]
- When adding a new workout https://verloorjouboep.feedmybeta.com/wp-admin/post-new.php?post_type=workout
- If you add a new exercise to a group, the video field does not list videos as you type
- Only after the post was saved are you able to connect video to the new exercises you added.
- See video: https://www.loom.com/share/b36e47ba4ce141eebc8253e90781f3a7

**Related Links**
- BugHerd: https://www.bugherd.com/projects/180675/tasks/9

**Comment by krugazul** [comment]
@ignusvermaak I have fixed the JS for [this](https://lsx-health-plan.lsdev.biz/wp-admin/post-new.php?post_type=workout),  it will trigger the `post_ajax_search` on new posts,  and when you edit posts, and add a new video section.
![Screenshot 2019-10-31 at 07 55 35](https://user-images.githubusercontent.com/1805603/67922633-f767bf00-fbb3-11e9-9df0-3350c53f2f34.png)

**Comment by ignusvermaak** [comment]
Fix tested and closing issue
