### ISSUE TITLE
When deleting/trashing recipes they still stay on the day plan in the back-end

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#20]
### Issue Description

When you trash a recipe (or any LSX HP post type) that has already been linked to a day it still stays on the day plan which results in an empty recipes tab content on the day.

Tested on Verloor jou boep - https://verloorjouboep.feedmybeta.com/plan/vrydag/recipes/

![image](https://user-images.githubusercontent.com/35291167/67780524-dd709400-fa6e-11e9-99b2-02c89454f5b2.png)

### Solution Needed

- [x] Add in a filter to the WP [action](https://developer.wordpress.org/reference/hooks/trashed_post/) `trashed_post`.
- [x] Check to see if the current post being trashed is one of the LSX HP post types.
- [x] If it is check what post type it is and if it has connections to any other post types.
- [x] Run through those connected post IDs, and remove the ID of the deleting post. (breaking the connection)
- [x] Test this by deleting a recipe and making sure the post ID is not there.

**Comment by krugazul** [comment]
@ashleyshaw I have added in a patch which checks to see if the IDs exists before trying to use them.  This fixes the frontend, but does not fix the larger problem thats the IDs are still stored in the custom fields.  I have detailed what needs to be done in the original comment.

**Comment by viscosho** [comment]
@krugazul  I have tested this branch, and I have deleted some recipes and test the entire pages connecto on the front and on the back, this is working correctly and its ready to be merged.

**Comment by krugazul** [comment]
@viscosho this fix was committed to the master branch.  That will not happen in future for issues.  I am closing this.
