### ISSUE TITLE
Edit my account stats fields needs updated styling.

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#21]
The styling for the stats fields in the my account - edit view is currently broken.

Reported on Verloor jou boep
![image](https://user-images.githubusercontent.com/35291167/67781007-8ae3a780-fa6f-11e9-9755-e604ce0fb431.png)
https://verloorjouboep.feedmybeta.com/my-plan/edit-account/

**Comment by krugazul** [comment]
I have checked the commit and tested the columns, its displaying properly now.
