### ISSUE TITLE
Day Plan on Tablet - Styling issue with days

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#22]
**Describe the bug**
When viewing the day plan on tablet size the last day of each week will sit on the very end this is caused by die `justify-content: space-around` style as seen here:

**To Reproduce**

1. Go to My Plan
2. Open Week 2 dropdown
3. Resize browser to Tablet Size or to 768px window size

**Expected behaviour**
The last days should not sit on the end of the list as it currently does.

**Screenshot**
![image](https://user-images.githubusercontent.com/35291167/67858929-0fdbc900-fb23-11e9-91a7-bb96850400ea.png)
https://verloorjouboep.feedmybeta.com/my-plan/

**Desktop** 
- Displaying fine

**Tablet** 
- Last day is showing at the end

**Mobile**
- Displaying fine

**Comment by krugazul** [comment]
@jacquesvdhorst ive checked the Code and tested the CSS on VJB, the day circles are listing properly now.
![Screenshot 2019-11-07 at 07 29 31](https://user-images.githubusercontent.com/1805603/68363179-a404ec00-0132-11ea-93fa-9ce36cb9603c.png)
