### ISSUE TITLE
Add plugin setting for linking "warm up page" through templates globally

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#23]
Currently we need to manually connect the "warm up page", it would save time on content management if we could simply link this via a global plugin setting.

**Comment by krugazul** [comment]
@ashleyshaw I am closing this issue,   I raised a similar one #24 , which covers a default warm up, recipe, workout and meal plan.  So you dont have to assign one to each day plan.
