### ISSUE TITLE
Add in setting to disable/enable fitness scores on profile and edit profile

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#29]
Currently there is no option to disable this should the site not want or use it. Only method is to hide the fields with styling.

[Bugherd Bug
](https://www.bugherd.com/projects/180675/tasks/39)
**Screenshots**
Account
![image](https://user-images.githubusercontent.com/35291167/68205977-48bce780-ffd4-11e9-9a01-673a72d85fd1.png)

Edit Account
![image](https://user-images.githubusercontent.com/35291167/68206029-6427f280-ffd4-11e9-8e51-0eb23de04e84.png)

It would be great we we can add this to the `LSX Health Plan Options` section that was introduced with the default plans and downloads.

**Comment by krugazul** [comment]
@jacquesvdhorst please do the following for this.

[Settings](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-settings.php#L118)
- [ ] Create a new section, called "My Profile Fields"  and add a checkbox to it. with a label of `Fitness`
- [ ] Make sure to have the checkbox `on` by default.
- [ ] Add in a description for the panel, `Enable or disable fields on your profile`.

Frontend
- [ ] Edit the [function](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-woocommerce.php#L510) which returns the array of profile fields, here you will get the fitness field setting, and test if it is on or off.
- [ ] If it is enabled,  then include the fitness fields.
