### ISSUE TITLE
Add in a setting to be able to set the tab endpoint names, for translations

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#30]
We are going to need to be able to translate the tabs on the single plan page.

**Settings**
- [x] Add in a new section, and a text input setting for each tab, this will house the endpoint slug.
- [x] The default value of the field will need to be the english slug.
- [x] This section will need a description, it will need to explain that you need to resave your permalinks after changing the endpoint settings.
- [x] Each setting name will need to prefixed with `endpoint_`  e.g `endpoint_warm_up`

Look [here](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-settings.php#L118) for settings we have already added in.

**[Endpoint Class](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-endpoints.php#L52)**
- [x] You need to get the endpoints setting, and use that, in the `add_rewrite_rule` instead of it being hard coded. This needs to happen for all 4 of the tabs.

**[Frontend](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/templates/single-plan-tabs.php#L13)**
- [x] Edit the `single-plan-tabs.php` template and make sure these pull through the setting value as well, otherwise default to the english slug.

**Testing**
 - [x] Test the endpoints in english
 - [x] Test Translating the endpoints and save the permalinks.

**Comment by jacquesvdhorst** [comment]
I've added in the settings and code changes to be able to translate the endpoints for URLS in Health Plan.

**Comment by krugazul** [comment]
@jacquesvdhorst I have tested and closed the Issue, the endpoint translations are working correctly.  

Description of the Change
 - We have added in settings to allow you to set the endpoint slugs, thereby allowing you to translate to links.

Benefits
 - Set the "Warm Up" tab slug
 - Set the "Workout" tab slug
 - Set the "Meal Plan " tab slug
 - Set the "Recipe" slug
 - Set the "Login" slug
 - Set the "My Plan" slug (for the redirect)

Checklist:
 - [x] The code follows the code style of this project.
 - [x] The change requires a change to the documentation.
 - [x] All new and existing tests passed.
