### ISSUE TITLE
Add a toggle for the Warm-up download button on workout tab

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#31]
**Description**
We need to add a setting where we can toggle the download button on and off for the workout tab.

[Bugherd Bug](https://www.bugherd.com/projects/180675/tasks/204)

**Screenshots**
![image](https://user-images.githubusercontent.com/35291167/68576778-62987780-0477-11ea-95e4-361761a3a963.png)
Button Location

**Comment by viscosho** [comment]
See pull Request: https://github.com/lightspeeddevelopment/lsx-health-plan/pull/64

**Comment by jacquesvdhorst** [comment]
@viscosho Everything is working as expected.
