### ISSUE TITLE
Create plugin settings to allow a user to disable the post types

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#35]
**Checkboxes on the plugin settings page **
Add in an additional box with a list of checkboxes, one for each post type. Here the user will be able to disable the post types they do not want active.

**Describe alternatives you've considered**
We will have filters which allow you to do this,  but most users are not code savy, so [plugin settings](https://lsx-health-plan.lsdev.biz/wp-admin/options-general.php?page=lsx_health_plan_options) are easier for them.

**What should happen**
- [x] A user clicks the checkbox and saves the settings page.
- [x] The tab for the post type should not appear on the plan page.
- [x] All visible connections on the frontend should not be visible.  e.g If tips are disabled the carousel should not show.
- [x] Any blocks registered for that post type should not appear in the backend.
- [x] Any meta boxes in the backend for this post type should not show.  e.g if recipes is disabled then the "connection" on the plan should not show.
- [ ] Disable the tips, recipes and workouts shortcode if the tip post type is disabled.

**Comment by viscosho** [comment]
@krugazul there is just 1 thing missing for this, disabling the tips, recipes and workout shortcodes.

- [x] Disable the tips, recipes and workouts shortcode if the tip post type is disabled. 
- [x] Push to the pull request #43

**Comment by krugazul** [comment]
@viscosho ive tested, and the shortcode are being disabled.  They will still show as text. because the block which has the shortcode need to be deleted.  See below with `video` disabled.

![Screenshot 2020-01-17 at 02 37 54](https://user-images.githubusercontent.com/1805603/72574711-a920ad00-38d2-11ea-9fbd-f858b87fbf19.png)
