### ISSUE TITLE
Add a download list to the weekly plan block

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#36]
**A download list**
We would like the option to include the downloads on the weekly plan block itself. We do not want it on all projects so it should be disabled by default.  You would need to enable a checkbox to add the download list to the block shortcode.

![Screenshot 2020-01-09 at 20 21 42](https://user-images.githubusercontent.com/1805603/72100152-ca115d00-332a-11ea-8597-a049b6ff3128.png)

**What should happen**
- [x] Create a setting in the block to include a "downloads" list box. There will be no firther options in the block for this.
- [x] Create a filter to allow the week view to include the downloads if the option has been specified.
- [x] Desktop, Mobile and Tablet views need to be taken into account.

**Comment by deonschreiber** [comment]
@viscosho and @krugazul Note the "Daily Plan" title and new icon. 
Invision link:https://projects.invisionapp.com/d/main#/console/17434990/400787359/preview

### Screenshot
![screenshot-weeklyplan-downloads](https://user-images.githubusercontent.com/31090573/72426526-8f784c00-3792-11ea-8b8e-ce73b9d00bf3.png)

**Comment by viscosho** [comment]
@krugazul  I have created a branch for this: https://github.com/lightspeeddevelopment/lsx-health-plan/tree/add/36 
The basic structure is ready, including the option on the plugin settings to turn this view on and off, and the respective styles.
Since there is no actual downloads assigned to a week, just for each day, I added a static list for the download section, and like we discussed, I'm assigning this to you for further development.

**Comment by krugazul** [comment]
@viscosho after reviewing the content,  I have come up with a plan for this section.  It should be quite simple to implement, as most of the backend work is there already.

We are going to use the "Download Categories" taxonomy that is already added by the "Downloads Monitor" plugin.   We will add a download to a category called "Week 1".
![Screenshot 2020-01-20 at 17 32 43](https://user-images.githubusercontent.com/1805603/72738741-e8891b00-3baa-11ea-9801-f72fbec1482e.png)

Then in the my plan week block, where you have already added [the code](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/add/36/includes/template-tags.php#L469), we will query the downloads using the current week name being cycled through.

I thought about extending the Week taxonomy to the downloads post type as well, but that could make more problems than we need.  Using their taxonomy is fine.

**Comment by viscosho** [comment]
@krugazul  I have tested this on my local and on the dev site, it is working as expected
