### ISSUE TITLE
Please change all the kg's in the boxes to just kg (no plural)

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#37]
Please change all the kg's in the boxes to just kg
[https://www.bugherd.com/projects/180675/tasks/359](https://www.bugherd.com/projects/180675/tasks/359)

![screenshot](https://user-images.githubusercontent.com/1805603/72244247-8ce0ef80-35f6-11ea-851c-60f3a16d211e.jpg)

**Comment by deonschreiber** [comment]
This has been updated - https://projects.invisionapp.com/d/main#/console/17434990/361937050/preview
### Screenshot
![screenshot-remove-plurals-edit-account](https://user-images.githubusercontent.com/31090573/72427317-28f42d80-3794-11ea-9e87-e881733a8210.png)

Please note: that this change also reflects on the "My Plan" tab
### Screenshot
![screenshot-remove-plurals-my-plan](https://user-images.githubusercontent.com/31090573/72427343-390c0d00-3794-11ea-97c4-d27bbc6cf93e.png)

**Comment by viscosho** [comment]
@krugazul  @deonschreiber  there is a PR now with this fixes: https://github.com/lightspeeddevelopment/lsx-health-plan/pull/44
