### ISSUE TITLE
Please change all the cm's in the boxes to just cm (No plural)

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#38]
Please change all the cm's in the boxes to just cm
(No plural)
[https://www.bugherd.com/projects/180675/tasks/360](https://www.bugherd.com/projects/180675/tasks/360)

![screenshot](https://user-images.githubusercontent.com/1805603/72244330-b6018000-35f6-11ea-967f-8e6646752f4a.jpg)

**Comment by viscosho** [comment]
@krugazul  @deonschreiber  there is a PR now with this fixes: https://github.com/lightspeeddevelopment/lsx-health-plan/pull/44
