### ISSUE TITLE
Separate the "Snack" boxes from the Meal Plan columns

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#39]
Separate the "Snack" boxes from the Meal Plan columns, (e.g image below) must be separate box, not part of breakfast
[https://www.bugherd.com/projects/180675/tasks/176](https://www.bugherd.com/projects/180675/tasks/176)

![screenshot](https://user-images.githubusercontent.com/1805603/72246092-ad12ad80-35fa-11ea-8840-ee758ba73f4c.jpg)

**Comment by deonschreiber** [comment]
This has been updated - https://projects.invisionapp.com/d/main#/console/17434990/400793365/preview

### Screenshot
![screenshot-mealplan-snack-after](https://user-images.githubusercontent.com/31090573/72428462-6a85d800-3796-11ea-8fe9-0181f053dc44.png)

**Comment by viscosho** [comment]
@krugazul  @deonschreiber  I have created a branch and a PR for this one: https://github.com/lightspeeddevelopment/lsx-health-plan/pull/45
