### ISSUE TITLE
The upload avatar pop up is being affected by the current page styling.

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#40]
***Problem***
If you [edit your account](https://lsx-health-plan.lsdev.biz/my-plan/edit-account/), and you select "Choose Image" button,  the WP pop up that shows has some areas that are affected by the current page styling.

- [x] [Select button](https://www.bugherd.com/projects/180675/tasks/27) at the bottom right hand corner.
- [x] The Text on the modal is not correct.
- [x] There are grey spaces below each image,
- [x] Each image has a border on it.

![Screenshot 2020-01-13 at 13 56 13](https://user-images.githubusercontent.com/1805603/72254371-83fb1880-360c-11ea-9fe7-8c679c180919.png)

**Comment by viscosho** [comment]
Fixes for this issue are on this branch: https://github.com/lightspeeddevelopment/lsx-health-plan/tree/fix/40
Please test

**Comment by jacquesvdhorst** [comment]
@viscosho @krugazul I've tested this on a local clean install. Working as intended.
