### ISSUE TITLE
Add in a "pre" snack field to the Meal Plan

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#41]
***Problem***
Some of the sites using LSX HP have a "snack" before and after breakfast, lunch or supper.

***Solution***
- [x] Duplicate the "Snack" [meta field](https://lsx-health-plan.lsdev.biz/wp-admin/post.php?post=2595&action=edit&classic-editor) on the meal plan post type, and add one before the breakfast, lunch and supper fields.
- [x] Rename the `Breakfast Snack` field to `Post-breakfast Snack` and `Pre-breakfast Snack
- [x] In the [frontend](https://lsx-health-plan.lsdev.biz/plan/day-1/meal/), duplicate the call for the current snack field, and use those for the pre snack field.
- [x] On the frontend name the both of them "Snack" for now, but pass them through a filter so child themes can change them if they need to.  ```apply_filters( 'lsx_hp_pre_snack_title', $title );```

***Testing***
- [x] If no text is entered, then the pre snack should not show, or the title.
- [x] If there is text entered then it should show, and the text should be formatted.
- [x] Is the information showing in the correct place.

![Screenshot 2020-01-14 at 15 26 30](https://user-images.githubusercontent.com/1805603/72348458-24237100-36e3-11ea-82ca-41944623be98.png)

![Screenshot 2020-01-14 at 15 33 44](https://user-images.githubusercontent.com/1805603/72348526-4a491100-36e3-11ea-84ee-3e2ed92bbe15.png)

**Comment by deonschreiber** [comment]
This has been updated in design

### Screenshot
![screenshot-mealplan-snack-before](https://user-images.githubusercontent.com/31090573/72428539-94d79580-3796-11ea-814b-15f9f8d23839.png)
