### ISSUE TITLE
The recipes archive needs to handle the LSX Search plugin

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#42]
## Problem
Currently the [recipes archive](https://lsx-health-plan.lsdev.biz/recipes/) is not searchable or sortable.

## Solution
We are going to integrate the recipes post type with the LSX Search Plugin

### Setup
- [x] Create a new class `class-lsx-search.php`, similar to the [class-woocommerce.php](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-woocommerce.php) already there. 
- [x] Create a new [function](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-integrations.php#L110) initiating the class and add a new [add_action](https://github.com/lightspeeddevelopment/lsx-health-plan/blob/master/classes/class-integrations.php#L62)
- [x] This class should only be included if the FacetWP plugin is enabled.

### Backend
- [x] Create a new setting panel for the recipe search settings, we will need a setting for each of the following field in the screenshot.
- [x] We will prefix the field names with `recipe_` but all all of the fields will use the same names as LSX uses.
![Screenshot 2020-01-14 at 21 53 25](https://user-images.githubusercontent.com/1805603/72378297-c52d1e80-3719-11ea-8680-41fc438b2959.png)

### Frontend
- [x] Edit the setup function, and allow the LSX HP plugin to allow the recipe post type for LSX.
- [x] Filter the search options variable and insert our recipes setting values.

The filters needed to be filtered are [here](https://github.com/lightspeeddevelopment/lsx-search/blob/master/classes/class-lsx-search-frontend.php#L85), the frontend will follow the LSX Search design.
![Screenshot 2020-01-14 at 22 05 58](https://user-images.githubusercontent.com/1805603/72378451-13422200-371a-11ea-99b4-e21840daf660.png)

### Testing
- [x] Install FacetWP
- [x] Setup the facets and index the site.
- [x] Setup the settings in the LSX HP Settings page.
- [x] Test filtering the facets on the frontend.
- [x] Test using the pagination
- [x] Test using the sorting.

#### Facets
- [x] Title (text search)
- [x] Prep time (single slider, per min)
- [x] Cooking time (single slider, per min)
- [x] Serves ( radio buttons, only 1 selection allowed )
- [x] Portion size ( radio buttons, only 1 selection allowed )

**Comment by deonschreiber** [comment]
@krugazul screenshot of the 1st draft for this is attached. 
![Recipe Landing Page](https://user-images.githubusercontent.com/31090573/72422331-ea0daa00-378a-11ea-8026-0f7a3b73972f.png)

**Comment by krugazul** [comment]
@deonschreiber the design looks great,  but yes the facets need to change please.  
Remove the "Meal Type"  we do not have a taxonomy or field for this on recipes.

These are possible facets
-  Prep time ( range  slider, per min)
-  Cooking time ( range slider, per min)
-  Serves ( only 1 selection allowed )
-  Portion size ( only 1 selection allowed, radio | dropdown | single slider )
