### ISSUE TITLE
The recipe type taxonomy needs to look like the recipe landing page

### ISSUE THREAD

**Issue by krugazul** [lightspeeddevelopment/lsx-health-plan#49]
**Problem**
We need to highlight certain recipes via a separate [URL](https://lsx-health-plan.lsdev.biz/recipe-type/meat-free/), e.g a list of Paleo recipes.

**Solution**
We are going to use the "Type" taxonomy term page and style it like the post type archive. It will not integrate with LSX Search though.

**To Do**
- [x] Add the taxonomy redirect for the Type Template
- [x] Copy the post type archive template and convert it into a taxonomy template.
- [x] Change "Type" in the Breadcrumbs to "Recipes" and link to the post type archive.
- [x] Move the description to below the banner
- [x] Change the term page title to "{term_name} Recipes".
- [x] Add the neccesary CSS Classes to the stylesheet to handle the archive.

![Screenshot 2020-01-17 at 17 36 37](https://user-images.githubusercontent.com/1805603/72628461-08c09c00-3957-11ea-8d9e-533119f9b32b.png)

**Comment by viscosho** [comment]
This has been reviewed on my local environment and test environment, all working ok.
