### ISSUE TITLE
Design Updates to Recipes Cards

### ISSUE THREAD

**Issue by deonschreiber** [lightspeeddevelopment/lsx-health-plan#54]
**Problem**
Recipes cards are a bit sparse...How do we make better use of the recipes metadata?

**Example Screenshot**
![Screenshot 2020-01-22 at 16 01 00](https://user-images.githubusercontent.com/31090573/72900375-6fb3cb80-3d30-11ea-8540-22ed9802494e.png)

**Solution**
Display the metadata connected with recipes on the cards, include icons and move the "recipes type" label into a badge overlaid on the image

![Screenshot 2020-01-22 at 16 04 21](https://user-images.githubusercontent.com/31090573/72900641-f36db800-3d30-11ea-911e-e313919237a9.png)

**Next Steps**
Assigned to dev for implementation and styling

**Comment by viscosho** [comment]
@krugazul  @deonschreiber  I have created a branch and a PR for this improvements: https://github.com/lightspeeddevelopment/lsx-health-plan/pull/56
You can test on the dev site: https://lsx-health-plan.lsdev.biz/recipe-type/red-meat/
https://lsx-health-plan.lsdev.biz/recipes/

**Comment by krugazul** [comment]
@viscosho I have reviewed the pull request and merged the branch in.
