### ISSUE TITLE
The fields that show the connections to other CTPs on each of the single edit screen are not showing content, nor you can update or change content.

### ISSUE THREAD

**Issue by ashleyshaw** [lightspeeddevelopment/lsx-health-plan#59]
**Describe the bug**
After updating CMB2 and Woocommerce, the fields that show the connections to other CTPs on each of the single edit screen are not showing content, nor you can update or change content.

**To Reproduce**
1. Go to any of the Health Plan CTP (recipes, workouts, plan, etc)
2. Go to a single post type.
3. Scroll down to the details section.

**Expected behavior**
The fields should show the connections to the other custom post types and should be able to add more or delete existent.

**This is how the Custom Fields look now (broken)**
<img width="1019" alt="Screen Shot 2020-01-28 at 3 56 33 PM" src="https://user-images.githubusercontent.com/3129483/73295876-463ee800-41e7-11ea-8b60-776af599270c.png">

**This is how the Custom Fields should look**
<img width="969" alt="Screen Shot 2020-01-28 at 4 01 30 PM" src="https://user-images.githubusercontent.com/3129483/73295994-81d9b200-41e7-11ea-8859-3beb61e9d616.png">

**Desktop (please complete the following information):**
 - All Browsers

**Smartphone (please complete the following information):**
 - All Devices

**Additional context**
This has something to do with the latest version of CMB2 or Woocommerce, since it happened after updating both.

[https://www.bugherd.com/projects/168385/tasks/201](https://www.bugherd.com/projects/168385/tasks/201)

**Comment by krugazul** [comment]
@ashleyshaw and @viscosho the issue has been solved,  it was the class name we use to check if CMB2 is available before adding the functions.   I changed it so it will be compatible in future when it is upgraded.

![Screenshot 2020-01-29 at 23 50 58](https://user-images.githubusercontent.com/1805603/73400653-4081f900-42f2-11ea-83b0-22703d936aa2.png)
