### ISSUE TITLE
LSX HP - change My Stats field to optional

### ISSUE THREAD

**Issue by garthglaum** [lightspeeddevelopment/lsx-health-plan#66]
**Describe the bug**
The My Stats fields are currently required fields.  This prevents users from saving their profile if they do not to want to enter this information.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://loseit.co.za/my-plan/edit-account/
2. Click on Account Details
3. Scroll down to My Stats
4. Leave some fields blank
5. Click Save Changes
6. See error messages at top of the page

<img width="853" alt="Screenshot 2020-02-10 at 15 49 23" src="https://user-images.githubusercontent.com/31071701/74155273-f582b280-4c1c-11ea-9b7c-7f4113014a41.png">

**Expected behaviour**
After entering the stats information, the new fields should be reflected at the top of the page.  If not information is entered then there should be NO error message

**Screenshots**
See above.

**Desktop (please complete the following information):**
 - All desktop browsers

**Mobile (please complete the following information):**
 - All mobile devices

**Comment by jacquesvdhorst** [comment]
@garthglaum I've applied the fix to the core. Setting for Review.
