### ISSUE TITLE
PHP issue: strtolower() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by viscosho** [lightspeeddevelopment/lsx-health-plan#74]
### Describe the bug

PHP issue:  `strtolower() expects parameter 1 to be string, array given`

Happening on:
lsx_health_plan_week_plan_block() -> wp-content/plugins/lsx-health-plan/includes/shortcodes.php:64
the_content() -> wp-content/plugins/lsx-health-plan/templates/page-template-my-plan.php:52

### Steps to Reproduce

1. Go to a page that has a HP shortcode like 'My Plan' page
2. Then go to the server and check the debug log
3. See the error registered
4. Also you can see this error on the front using a debug plugin like Query Monitor

### Environment information
 - Device: MacBook
 - OS: MacOS
 - Browser and version: Chrome
 - Theme and version: Latest LSX
- WordPress version: Latest WP

**Comment by krugazul** [comment]
@viscosho  the `get_terms` function does not accept an array for the `orderby` parameter,  thats where the error was coming from.  I changed that to just `menu_order`.
