### ISSUE TITLE
Change "Video" column to "How to"

### ISSUE THREAD

**Issue by garthglaum** [lightspeeddevelopment/lsx-health-plan#81]
### Is your enhancement related to a problem? Please describe.
No

### Describe the solution you'd like
On the workout, change the column heading **Video** to **How To**
See screenshot:

![Screenshot 2020-04-14 at 16 11 02](https://user-images.githubusercontent.com/31071701/79234491-9fbfc600-7e6a-11ea-9b95-54fb85b8ec87.png)

**Comment by krugazul** [comment]
@garthglaum  this has been changed - https://lsx-health-plan.lsdev.biz/plan/day-1/workout/
