### ISSUE TITLE
Placeholder text in the Waist fields need to change to cm

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/lsx-health-plan#9]
**Reported on** https://klopdieskaal.feedmybeta.com/my-plan/edit-account/

The placeholder text in the second row - Waist fields are showing kg's instead of cm.

**Reference:**

![Screenshot 2019-09-13 at 13 48 03](https://user-images.githubusercontent.com/35291167/64860339-268a9700-d62d-11e9-9b2c-4706e8bc6be6.png)

**Comment by viscosho** [comment]
@jacquesvdhorst  please review, this has been changed here: https://github.com/lightspeeddevelopment/lsx-health-plan/commit/9f814f3e28e1a8bfe9f4e2b7cec52692d917d5df
